name: Build and test

on:
  push:
    branches:
      - "main"
      - "staging"

  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.14.0
          - 4.10.2

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          cache-prefix: v1-${{ matrix.os }}
          opam-local-packages: bio_io.opam

      - run: opam install ./bio_io.opam --deps-only --with-doc --with-test

      # Check the dev profile.
      - run: opam exec -- make clean
      - run: opam exec -- make build_dev
      - run: opam exec -- make test_dev
      - run: opam exec -- make install_dev

      # Check the release profile.
      - run: opam exec -- make clean
      - run: opam exec -- make build_release
      - run: opam exec -- make test_release
      - run: opam exec -- make install_release

      # Install bisect_ppx if we are sending coverage.
      - run: opam install bisect_ppx
        if: matrix.ocaml-compiler == '4.14.0'

      # Send the coverage.
      - run: opam exec -- make send_coverage
        if: matrix.ocaml-compiler == '4.14.0'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
