name: Generate Docs

on:
  push:
    branches:
      - '*'

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mooreryan/bio_io_generate_docs:b7e69b8

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # New dependency for 0.3.0.  You can remove this once you update
      # the Docker image.
      - run: opam install ppx_compare

      - run: make docs_site
      - run: git checkout gh-pages
      - run: if [ -d docs ]; then rm -r docs; fi
      - run: mv _docs docs

      - name: Commit site changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add docs
          git commit -m "Update docs site"
          git push
