name: Generate Docs

on:
  push:
    branches:
      - '*'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use OCaml 4.12.0
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0
          dune-cache: true
          cache-prefix: v1-ubuntu-latest-4.12.0

      - run: opam install . --deps-only --with-doc

      - run: make docs_site
      - run: git checkout gh-pages
      - run: if [ -d docs ]; then rm -r docs; fi
      - run: mv _docs docs

      - name: Commit site changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add docs
          git commit -m "Update docs site"
          git push
